title:             知与行
email:             maoshuainan@gmail.com
description:       谨言慎行 惜时勤学
author:            毛帅男
baseurl:           "/"
url:               "http://maoshuainan.github.io"

# Social Profiles
twitter_username:  
github_username:   maoshuainan
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
